# Streamlit Secrets Configuration
# Replace these with your actual API keys

# OpenRouter API Key (for OpenAI models)
OPENROUTER_API_KEY = "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"

# Supabase Configuration
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zdHN1emFibnp0cXJpdXJlZW9pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNTE1MTksImV4cCI6MjA3MTcyNzUxOX0.lHjfHAQVCnxGePPAQAFkOkR0nsF29A7gqCaox67InZE"
# Note: Use the anon/public key, not the service_role key for client-side access
