# Streamlit Secrets Configuration
# Replace these with your actual API keys

# OpenRouter API Key (for OpenAI models)
OPENROUTER_API_KEY = "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"

# Supabase Configuration
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zdHN1emFibnp0cXJpdXJlZW9pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNTE1MTksImV4cCI6MjA3MTcyNzUxOX0.lHjfHAQVCnxGePPAQAFkOkR0nsF29A7gqCaox67InZE"
# Note: Use the anon/public key, not the service_role key for client-side access
